FROM oven/bun:alpine AS base

# Stage 1: Install dependencies
FROM base AS deps
WORKDIR /app
# Copy only the necessary files for dependency installation
COPY package.json bun.lockb ./
# Install dependencies using Bun
RUN bun install


# Stage 2: Build application (The Builder Stage)
FROM base AS builder
WORKDIR /app
# Copy installed dependencies and source code
COPY --from=deps /app/node_modules ./node_modules
COPY . .

# CRITICAL FIX: Accept the DATABASE_URL build argument and set it as an environment variable
# This is necessary for Next.js to access database config during the 'bun run build' step
ARG DATABASE_URL
ENV DATABASE_URL=$DATABASE_URL

# Run the Next.js production build command
RUN bun run build

# Stage 3: Run production server (The Runner Stage)
# This stage is minimized to only contain the artifacts needed for runtime (Standalone Mode)
FROM base AS runner
WORKDIR /app
ENV NODE_ENV=production

# Copy only the production-ready files generated by the builder stage:
# 1. Public assets (images, fonts)
COPY --from=builder /app/public ./public
# 2. Next.js Standalone output (contains the compiled server.js and routes)
COPY --from=builder /app/.next/standalone ./
# 3. Static assets (.next/static)
COPY --from=builder /app/.next/static ./.next/static

EXPOSE 3000

CMD ["bun", "run", "server.js"]
